import 'package:geolocator/geolocator.dart';

class GlobalData{
  static Position locationPosition;
  static int locationId = -1;
  static final Map<int,String> locations = {
    0: "Hồ Chí Minh",
    1: "Hà Nội",
    2: "Đà Nẵng",
    3: "Hải Phòng",
    4: "Biên Hoà",
    5: "Nha Trang",
    6: "Bình Dương",
    7: "Phan Thiết",
    8: "Hạ Long",
    9: "Cần Thơ",
    10: "Vũng Tàu",
    11: "Quy Nhơn",
    12: "Huế",
    13: "Long Xuyên",
    14: "Thái Nguyên",
    15: "Buôn Ma Thuột",
    16: "Bắc Giang",
    17: "Bến Tre",
    18: "Việt Trì",
    19: "Ninh Bình",
    20: "Thái Bình",
    21: "Vinh",
    22: "Bảo Lộc",
    23: "Đà Lạt",
    24: "Trà Vinh",
    25: "Yên Bái",
    26: "Kiên Giang",
    27: "Vĩnh Long",
    28: "Cà Mau",
    29: "Hậu Giang",
    30: "Tây Ninh",
    31: "Tuyên Quang",
    32: "Thanh Hóa",
    33: "Nam Định",
    34: "Hải Dương",
    35: "Gia Lai",
    36: "Hà Tĩnh",
    37: "Phú Yên",
    38: "Bạc Liêu",
    39: "Long An",
    40: "Đồng Hới",
    41: "Hà Nam",
    42: "Bắc Ninh",
    43: "Quảng Trị",
    44: "Kon Tum",
  };

}